repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [ "--max-line-length=99",
                "--ignore=E731,E266,E501,C901,W503",
                "--exclude=.git,notebooks,references,models,data,__pycache__,venv",
                "--per-file-ignores=**/__init__.py: F401" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: [--exclude=__pycache__, --disallow-subclassing-any, --ignore-missing-imports]
