version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${USER_NAME}
      MINIO_ROOT_PASSWORD: ${PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    container_name: mlflow
    command: /usr/local/bin/mlflow server --backend-store-uri sqlite:///mlruns.db --default-artifact-root s3://mlflow/ --host 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${USER_NAME}
      AWS_SECRET_ACCESS_KEY: ${PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    env_file:
      - .env

volumes:
  minio_data:
